# Generated by Django 2.2.7 on 2019-12-19 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divisas', '0002_insertar_divisas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', help_text='Nombre de la actividad', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Ambito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', help_text='Nombre de la ambito', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'ambito',
                'verbose_name_plural': 'ambitos',
            },
        ),
        migrations.CreateModel(
            name='Clasificacion_gto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', help_text='Nombre de la ambito', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'clasificacion',
                'verbose_name_plural': 'clasificaciones',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='código único de cliente', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(db_column='nombre', help_text='Nombre de la empresa', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='codigo', help_text='Codigo empresa bi', max_length=20, unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(db_column='nombre', help_text='Nombre de la empresa', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', help_text='Nombre de la grupo', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', help_text='Nombre de la situacion', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'situacion',
                'verbose_name_plural': 'situaciones',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', help_text='Nombre de la zona', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'zona',
                'verbose_name_plural': 'zonas',
            },
        ),
        migrations.CreateModel(
            name='UnidadOrganizativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subunidades', to='general.UnidadOrganizativa')),
            ],
            options={
                'verbose_name': 'unidad organizativa',
                'verbose_name_plural': 'unidades organizativas',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='codigo', help_text='Codigo de la obra', max_length=20, verbose_name='codigo')),
                ('descripcion', models.CharField(db_column='descripcion', help_text='descripcion de la obra', max_length=20, verbose_name='descripcion')),
                ('obsoleta', models.BooleanField(default=False, help_text='indica si es una obra obsoleta', verbose_name='obsoleta')),
                ('bi', models.BooleanField(default=True, help_text='indica si se usará en los cálculos BI', verbose_name='se usará en BI')),
                ('codigo_estudio', models.CharField(help_text='código de estudio asociado', max_length=20, null=True, verbose_name='código de estudio')),
                ('tipo', models.BooleanField(default=True, help_text='indica si es una obra o un servicio', verbose_name='obra')),
                ('activo', models.BooleanField(default=True, help_text='indica si está activa', verbose_name='activo')),
                ('plazo', models.IntegerField(default=0, help_text='plazo inicial oficial en meses', verbose_name='plazo inicial oficial')),
                ('prorroga', models.IntegerField(help_text='prórrogas aprobadas en meses', null=True, verbose_name='prórrogas aprobadas')),
                ('fecha_fin', models.DateField(help_text='fecha del fin de obra oficial', null=True, verbose_name='fecha de fin oficial')),
                ('fecha_prevista_fin', models.DateField(help_text='fecha prevista real del fin de obra', null=True, verbose_name='fecha prevista de fin')),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0.0, help_text='importe del presupuesto de adjudicación', max_digits=14, verbose_name='presupuesto de adjudicación')),
                ('ampliacion', models.DecimalField(decimal_places=2, help_text='importe de las ampliaciones de presupuesto', max_digits=14, null=True, verbose_name='ampliaciones de presupuesto')),
                ('actividad', models.ForeignKey(blank=True, help_text='actividad a la que pertence la obra', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='general.Actividad', verbose_name='actividades')),
                ('ambito', models.ForeignKey(blank=True, help_text='ambito a la que pertence la obra', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='general.Ambito', verbose_name='ambitos')),
                ('clasificacion', models.ForeignKey(blank=True, help_text='clasificacion a la que pertence la obra', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='general.Clasificacion_gto', verbose_name='Clasificaciones')),
                ('cliente', models.ForeignKey(help_text='cliente a la que pertence la obra', on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='general.Cliente', verbose_name='clientes')),
                ('divisa', models.ForeignKey(default=2, help_text='divisa asociada', on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='divisas.Divisa', verbose_name='divisa')),
                ('empresa', models.ForeignKey(help_text='empresa a la que pertence la obra', on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='general.Empresa', verbose_name='empresas')),
                ('grupo', models.ForeignKey(blank=True, help_text='grupo a la que pertence la obra', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='general.Grupo', verbose_name='grupos')),
                ('responsables', models.ManyToManyField(blank=True, help_text='responsables', related_name='obras', to=settings.AUTH_USER_MODEL, verbose_name='usuario con perfil responsable de obra')),
                ('situacion', models.ForeignKey(blank=True, help_text='situacion a la que pertence la obra', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='general.Situacion', verbose_name='situaciones')),
                ('zona', models.ForeignKey(blank=True, help_text='zona a la que pertence la obra', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='general.Zona', verbose_name='zonas')),
            ],
            options={
                'verbose_name': 'obra',
                'verbose_name_plural': 'obras',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='código único de empleado', max_length=50, unique=True, verbose_name='código')),
                ('responsable', models.ForeignKey(help_text='responsable del empleado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinados', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('usuario', models.OneToOneField(help_text='usuario asociado al empleado', on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='ParametroUnidadOrganizativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='año')),
                ('cuarto', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], verbose_name='cuatrimestre')),
                ('gasto_delegacion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% de gasto delegación')),
                ('gasto_central', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% de gasto central')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.UnidadOrganizativa', verbose_name='unidad')),
            ],
            options={
                'verbose_name': 'parametro de unidad organizativa',
                'verbose_name_plural': 'parametros de unidad organizativa',
                'unique_together': {('unidad', 'year', 'cuarto')},
            },
        ),
        migrations.CreateModel(
            name='CambioDivisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='año')),
                ('cuarto', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], verbose_name='cuatrimestre')),
                ('importe', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='importe del cambio respecto al EUR')),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='divisas.Divisa', verbose_name='divisa')),
            ],
            options={
                'verbose_name': 'cambio de divisa',
                'verbose_name_plural': 'cambios de divisa',
                'unique_together': {('divisa', 'year', 'cuarto')},
            },
        ),
    ]
