# Generated by Django 2.2.7 on 2019-12-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['codigo'], name='general_cli_codigo_83aec0_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['codigo'], name='general_emp_codigo_7245fe_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['codigo'], name='general_emp_codigo_f12cfa_idx'),
        ),
    ]
