# Generated by Django 2.2.7 on 2020-02-04 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20200120_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='ampliacion',
        ),
        migrations.AddField(
            model_name='obra',
            name='coste_previsto',
            field=models.DecimalField(decimal_places=2, help_text='importe del coste previsto', max_digits=14, null=True, verbose_name='coste previsto'),
        ),
        migrations.CreateModel(
            name='AmpliacionPresupuestoObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='fecha de la ampliación de presupuesto', verbose_name='fecha')),
                ('descripcion', models.TextField(help_text='descripción de la ampliación de presupuesto', null=True, verbose_name='descripción')),
                ('importe', models.DecimalField(decimal_places=2, help_text='importe de la ampliación de presupuesto', max_digits=5, verbose_name='importe')),
                ('obra', models.ForeignKey(help_text='obra de la ampliación de presupuesto', on_delete=django.db.models.deletion.CASCADE, related_name='ampliaciones_presupuesto', to='general.Obra', verbose_name='obra')),
            ],
            options={
                'verbose_name': 'ampliación de presupuesto de obra',
                'verbose_name_plural': 'ampliaciones de presupuesto de obra',
            },
        ),
        migrations.CreateModel(
            name='AmpliacionCosteObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='fecha de la ampliación de coste', verbose_name='fecha')),
                ('descripcion', models.TextField(help_text='descripción de la ampliación de coste', verbose_name='descripción')),
                ('importe', models.DecimalField(decimal_places=2, help_text='importe de la ampliación de coste', max_digits=5, verbose_name='importe')),
                ('obra', models.ForeignKey(help_text='obra de la ampliación de coste', on_delete=django.db.models.deletion.CASCADE, related_name='ampliaciones_coste', to='general.Obra', verbose_name='obra')),
            ],
            options={
                'verbose_name': 'ampliación de coste de obra',
                'verbose_name_plural': 'ampliaciones de coste de obra',
            },
        ),
    ]
