# Generated by Django 2.2.7 on 2020-02-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20200206_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='fecha del fin de obra oficial', null=True, verbose_name='fecha de fin oficial'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fecha_prevista_fin',
            field=models.DateField(blank=True, help_text='fecha prevista real del fin de obra', null=True, verbose_name='fecha prevista de fin'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='orden',
            field=models.IntegerField(blank=True, null=True, verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='prorroga',
            field=models.IntegerField(default=0, help_text='prórrogas aprobadas en meses', verbose_name='prórrogas aprobadas'),
        ),
    ]
