# Generated by Django 2.2.7 on 2020-02-07 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20200206_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='delegacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras_delegacion', to='general.UnidadOrganizativa', verbose_name='delegación'),
        ),
        migrations.AddField(
            model_name='obra',
            name='subdelegacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras_subdelegacion', to='general.UnidadOrganizativa', verbose_name='subdelegación'),
        ),
    ]
