# Generated by Django 2.2.7 on 2020-02-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_auto_20200207_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='nombre',
            field=models.CharField(db_column='nombre', help_text='Nombre de la zona', max_length=255, unique=True, verbose_name='nombre'),
        ),
    ]
