# Generated by Django 2.2.7 on 2020-02-07 13:41

from django.db import migrations

ZONAS = []


def insertar_zonas(apps, schema_editor):
    Zona = apps.get_model('general', 'Zona')
    for zona in ZONAS:
        instancia = Zona(nombre=zona)
        instancia.save()


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_auto_20200207_1441'),
    ]

    operations = [
        migrations.RunPython(insertar_zonas),
    ]
