# Generated by Django 2.2.7 on 2020-02-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_insertar_zonas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(db_column='nombre', help_text='Nombre de la actividad', max_length=255, unique=True, verbose_name='nombre'),
        ),
    ]
