# Generated by Django 2.2.7 on 2020-02-07 13:46

from django.db import migrations

ACTIVIDADES = []


def insertar_actividades(apps, schema_editor):
    Actividad = apps.get_model('general', 'Actividad')
    for actividad in ACTIVIDADES:
        instancia = Actividad(nombre=actividad)
        instancia.save()


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_auto_20200207_1445'),
    ]

    operations = [
        migrations.RunPython(insertar_actividades),
    ]
