# Generated by Django 2.2.7 on 2020-02-07 13:53

from django.db import migrations

SITUACIONES = []


def insertar_situaciones(apps, schema_editor):
    Situacion = apps.get_model('general', 'Situacion')
    for situacion in SITUACIONES:
        instancia = Situacion(nombre=situacion)
        instancia.save()


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_auto_20200207_1452'),
    ]

    operations = [
        migrations.RunPython(insertar_situaciones),
    ]
