# Generated by Django 2.2.7 on 2020-02-07 14:01

from django.db import migrations

AMBITOS = []


def insertar_ambitos(apps, schema_editor):
    Ambito = apps.get_model('general', 'Ambito')
    for ambito in AMBITOS:
        instancia = Ambito(nombre=ambito)
        instancia.save()


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_auto_20200207_1501'),
    ]

    operations = [
        migrations.RunPython(insertar_ambitos),
    ]
