# Generated by Django 2.2.7 on 2020-02-07 14:05

from django.db import migrations

CLASIFICACIONES_GTO = []


def insertar_clasificaciones_gto(apps, schema_editor):
    Clasificacion_gto = apps.get_model('general', 'Clasificacion_gto')
    for clasificacion in CLASIFICACIONES_GTO:
        instancia = Clasificacion_gto(nombre=clasificacion)
        instancia.save()


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_auto_20200207_1504'),
    ]

    operations = [
        migrations.RunPython(insertar_clasificaciones_gto),
    ]
