# Generated by Django 2.2.7 on 2020-02-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_insertar_clasificaciones_gto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unidadorganizativa',
            unique_together={('descripcion', 'padre')},
        ),
    ]
