# Generated by Django 2.2.7 on 2020-02-10 09:43

from django.db import migrations

PERFILES = []


def insertar_obras(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for indice, perfil in enumerate(PERFILES):
        instancia = Group(id=indice + 1, name=perfil)
        instancia.save()


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0023_auto_20200211_1049'),
    ]

    operations = [
        migrations.RunPython(insertar_obras),
    ]
