# Generated by Django 2.2.7 on 2020-02-11 10:59

from django.db import migrations

JEFE_OBRA = "Jefe de Obra"
RESPONSABLE = "Responsable"
ADMIN = "Administrador"

EMPLEADOS = []


def insertar_empleados(apps, schema_editor):
    Empleado = apps.get_model('general', 'Empleado')
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    admin = Group.objects.get(id=1)
    respo = Group.objects.get(id=2)
    jefe_obra = Group.objects.get(id=3)
    for empleado in EMPLEADOS:
        nombre = empleado["nombre"].split(sep=",")
        try:
            instancia = User(
                username=empleado["user"], email=empleado["email"], last_name=nombre[0], first_name=nombre[1])
        except IndexError:
            instancia = User(
                username=empleado["user"], email=empleado["email"], last_name=nombre[0])
        instancia.save()
        if empleado["perfil"] == ADMIN:
            instancia.groups.set([admin, ])
        elif empleado["perfil"] == RESPONSABLE:
            instancia.groups.set([respo, ])
        else:
            instancia.groups.set([jefe_obra, ])
        instancia_empleado = Empleado(
            usuario=instancia, codigo=empleado["codigo"])
        instancia_empleado.save()


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0024_insertar_perfiles'),
    ]

    # operations = [
    #     migrations.RunPython(insertar_empleados),
    # ]
