# Generated by Django 2.2.7 on 2020-02-11 11:21

from django.db import migrations

EMPRESAS = []


def insertar_empresas(apps, schema_editor):
    Empresa = apps.get_model('general', 'Empresa')
    for empresa in EMPRESAS:
        instancia = Empresa(codigo=empresa["codigo"],
                            nombre=empresa["descripcion"])
        instancia.save()


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0025_insertar_empleados'),
    ]

    operations = [
        migrations.RunPython(insertar_empresas),
    ]
