# Generated by Django 2.2.7 on 2020-02-11 11:21

from django.db import migrations
CLIENTES = []


def insertar_clientes(apps, schema_editor):
    Cliente = apps.get_model('general', 'Cliente')
    for cliente in CLIENTES:
        instancia = Cliente(
            codigo=cliente["codigo"], nombre=cliente["descripcion"])
        instancia.save()


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0026_insertar_empresas'),
    ]

    operations = [
        migrations.RunPython(insertar_clientes),
    ]
