# Generated by Django 2.2.7 on 2020-02-11 11:21

from django.db import migrations

OBRAS = []


def insertar_obras(apps, schema_editor):
    Obra = apps.get_model('general', 'Obra')
    Empresa = apps.get_model('general', 'Empresa')
    Cliente = apps.get_model('general', 'Cliente')
    Empleado = apps.get_model('general', 'Empleado')
    Zona = apps.get_model('general', 'Zona')
    Grupo = apps.get_model('general', 'Grupo')
    Actividad = apps.get_model('general', 'Actividad')
    Situacion = apps.get_model('general', 'Situacion')
    Ambito = apps.get_model('general', 'Ambito')
    Clasificacion_gto = apps.get_model('general', 'Clasificacion_gto')
    UnidadOrganizativa = apps.get_model('general', 'UnidadOrganizativa')
    Grupo = apps.get_model('general', 'Grupo')
    for obra in OBRAS:
        empresa = Empresa.objects.get(codigo=obra["empresa"])
        cliente = Cliente.objects.get(codigo=obra["cliente"])
        zona = Zona.objects.get(nombre=obra["zona"].strip())
        if obra["grupo"].strip() == "":
            grupo = Grupo.objects.get(nombre="S/D")
        else:
            grupo = Grupo.objects.get(nombre=obra["grupo"].strip())
        if obra["actividad"].strip() == "":
            actividad = Actividad.objects.get(nombre="S/D")
        else:
            actividad = Actividad.objects.get(nombre=obra["actividad"].strip())
        if obra["situacion"].strip() == "":
            situacion = Situacion.objects.get(nombre="S/D")
        else:
            situacion = Situacion.objects.get(nombre=obra["situacion"].strip())
        ambito = Ambito.objects.get(nombre=obra["ambito"].strip())
        clasificacion_gto = Clasificacion_gto.objects.get(
            nombre=obra["clasificacion_gto"].strip())
        if obra["delegacion"].strip() == "":
            delegacion = UnidadOrganizativa.objects.get(
                descripcion="S/D", padre__isnull=True)
            subdelegacion = UnidadOrganizativa.objects.get(
                descripcion="S/D", padre__isnull=False)
        else:
            delegacion = UnidadOrganizativa.objects.get(
                descripcion=obra["delegacion"].strip(), padre__isnull=True)
            subdelegacion = UnidadOrganizativa.objects.get(
                descripcion=obra["subdelegacion"].strip(), padre=delegacion)
        responsables = []
        if obra["respo1"].strip() != "":
            respo1 = Empleado.objects.get(codigo=obra["respo1"]).usuario
            responsables.append(respo1)
        if obra["respo2"].strip() != "":
            respo2 = Empleado.objects.get(codigo=obra["respo2"]).usuario
            responsables.append(respo2)
        if obra["respo3"].strip() != "":
            respo3 = Empleado.objects.get(codigo=obra["respo3"]).usuario
            responsables.append(respo3)
        instancia = Obra(codigo=obra["codigo"], descripcion=obra["descripcion"], empresa=empresa, cliente=cliente, zona=zona, grupo=grupo, actividad=actividad, situacion=situacion,
                         ambito=ambito, clasificacion=clasificacion_gto, obsoleta=obra["obsoleta"], bi=obra["bi"], codigo_estudio=obra["cod_estudio"], orden=obra["orden"], delegacion=delegacion, subdelegacion=subdelegacion)
        instancia.save()
        instancia.responsables.set(responsables)


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0027_insertar_clientes'),
    ]

    operations = [
        migrations.RunPython(insertar_obras),
    ]
