# Generated by Django 2.2.7 on 2020-02-14 09:23

from django.db import migrations

PRODUCCIONES = []


def insertar_produccion(apps, schema_editor):
    Obra = apps.get_model('general', 'Obra')
    for produccion in PRODUCCIONES:
        Obra.objects.filter(codigo=produccion["codigo"]).update(
            presupuesto=produccion["produccion"])


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0028_insertar_obras'),
    ]

    operations = [
        migrations.RunPython(insertar_produccion),
    ]
