# Generated by Django 2.2.7 on 2020-02-14 10:33

from django.db import migrations

COSTES = []


def insertar_coste(apps, schema_editor):
    Obra = apps.get_model('general', 'Obra')
    for coste in COSTES:
        Obra.objects.filter(codigo=coste["codigo"]).update(
            coste_previsto=coste["coste"])


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0029_insertar_produccion'),
    ]

    operations = [
        migrations.RunPython(insertar_coste)
    ]
