# Generated by Django 2.2.7 on 2020-05-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0030_insertar_costes'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='observaciones',
            field=models.TextField(blank=True, help_text='observaciones de la obra', null=True, verbose_name='observaciones'),
        ),
    ]
