# Generated by Django 2.2.7 on 2020-06-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0031_obra_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliacioncosteobra',
            name='importe',
            field=models.DecimalField(decimal_places=2, help_text='importe de la ampliación de coste', max_digits=14, verbose_name='importe'),
        ),
        migrations.AlterField(
            model_name='ampliacionpresupuestoobra',
            name='importe',
            field=models.DecimalField(decimal_places=2, help_text='importe de la ampliación de presupuesto', max_digits=14, verbose_name='importe'),
        ),
    ]
