# Generated by Django 2.2.7 on 2021-11-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0032_auto_20200604_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='participacion_licuas',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='participación licuas', max_digits=14, verbose_name='participación licuas'),
        ),
    ]
