# Generated by Django 2.2.7 on 2019-11-28 08:39

from django.db import migrations

DIVISAS = []


def insertar_divisas(apps, schema_editor):
    Divisa = apps.get_model('divisas', 'Divisa')
    for divisa in DIVISAS:
        instancia = Divisa(
            codigo=divisa['codigo'], descripcion=divisa['descripcion'])
        instancia.save()


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insertar_divisas),
    ]
