# Generated by Django 2.2.7 on 2020-01-20 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hdr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaderuta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hojaderuta',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de último modificación'),
        ),
        migrations.AddField(
            model_name='hojaderuta',
            name='usuario_creacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='hdr_creadas', to=settings.AUTH_USER_MODEL, verbose_name='usuario de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hojaderuta',
            name='usuario_modificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='hdr_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='usuario de última modificación'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='hojaderuta',
            index=models.Index(fields=['obra', 'year', 'cuarto'], name='hdr_hojader_obra_id_5658f3_idx'),
        ),
    ]
