# Generated by Django 2.2.7 on 2020-01-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0002_auto_20200120_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('coste', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='coste')),
                ('venta', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='venta')),
                ('hdr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objetivos', to='hdr.HojaDeRuta', verbose_name='hoja de ruta')),
            ],
            options={
                'verbose_name': 'objetivo',
                'verbose_name_plural': 'objetivos',
            },
        ),
    ]
