# Generated by Django 2.2.7 on 2020-01-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0003_objetivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetivo',
            old_name='hdr',
            new_name='hoja',
        ),
    ]
