# Generated by Django 2.2.7 on 2020-01-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0004_auto_20200120_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
    ]
