# Generated by Django 2.2.7 on 2020-01-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0005_auto_20200123_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='coste',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='coste'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='descripcion',
            field=models.TextField(verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='venta'),
        ),
    ]
