# Generated by Django 2.2.7 on 2020-01-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0006_auto_20200123_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hojaderuta',
            name='importe_coste_central_pendiente',
        ),
        migrations.RemoveField(
            model_name='hojaderuta',
            name='importe_coste_delegacion_pendiente',
        ),
        migrations.RemoveField(
            model_name='hojaderuta',
            name='importe_coste_directo_pendiente',
        ),
        migrations.AddField(
            model_name='hojaderuta',
            name='importe_coste_directo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='importe de costes directos e indirectos total'),
            preserve_default=False,
        ),
    ]
