# Generated by Django 2.2.7 on 2020-01-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0007_auto_20200124_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaderuta',
            name='observaciones',
            field=models.TextField(null=True, verbose_name='observaciones'),
        ),
    ]
