# Generated by Django 2.2.7 on 2020-01-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0008_hojaderuta_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaderuta',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='observaciones'),
        ),
    ]
