# Generated by Django 2.2.7 on 2020-02-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0009_auto_20200124_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaderuta',
            name='fecha_fin_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de fin de la entrega'),
        ),
        migrations.AlterField(
            model_name='hojaderuta',
            name='gasto_central',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% de gasto central'),
        ),
        migrations.AlterField(
            model_name='hojaderuta',
            name='gasto_delegacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% de gasto delegación'),
        ),
    ]
