# Generated by Django 2.2.7 on 2020-02-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0010_auto_20200206_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaderuta',
            name='importe_ampliacion_anterior',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='importe de ampliaciones hasta fin del año anterior'),
        ),
        migrations.AlterField(
            model_name='hojaderuta',
            name='importe_ampliacion_consolidado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='importe de ampliaciones consolidado durante el año'),
        ),
        migrations.AlterField(
            model_name='hojaderuta',
            name='importe_ampliacion_pendiente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='importe de ampliaciones pediente'),
        ),
        migrations.AlterField(
            model_name='hojaderuta',
            name='importe_contrato_anterior',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='importe de contrato inicial hasta fin del año anterior'),
        ),
        migrations.AlterField(
            model_name='hojaderuta',
            name='importe_contrato_consolidado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='importe de contrato inicial consolidado durante el año'),
        ),
        migrations.AlterField(
            model_name='hojaderuta',
            name='importe_contrato_pendiente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='importe de contrato inicial pediente'),
        ),
        migrations.AlterField(
            model_name='hojaderuta',
            name='importe_coste_central_anterior',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='importe de costes asociados a la central hasta fin del año anterior'),
        ),
        migrations.AlterField(
            model_name='hojaderuta',
            name='importe_coste_central_consolidado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='importe de costes asociados a la central consolidado durante el año'),
        ),
        migrations.AlterField(
            model_name='hojaderuta',
            name='importe_coste_delegacion_anterior',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='importe de costes asociados a la delegación hasta fin del año anterior'),
        ),
        migrations.AlterField(
            model_name='hojaderuta',
            name='importe_coste_delegacion_consolidado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='importe de costes asociados a la delegación consolidado durante el año'),
        ),
        migrations.AlterField(
            model_name='hojaderuta',
            name='importe_coste_directo_anterior',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='importe de costes directos e indirectos hasta fin del año anterior'),
        ),
        migrations.AlterField(
            model_name='hojaderuta',
            name='importe_coste_directo_consolidado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='importe de costes directos e indirectos consolidado durante el año'),
        ),
        migrations.AlterField(
            model_name='hojaderuta',
            name='importe_coste_directo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='importe de costes directos e indirectos total'),
        ),
    ]
