# Generated by Django 2.2.7 on 2020-02-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0012_auto_20200206_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaderutacertificacion',
            name='importe_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de certificación hasta fin del año anterior'),
        ),
        migrations.AlterField(
            model_name='hojaderutacertificacion',
            name='importe_mes_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de certificación para el primer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutacertificacion',
            name='importe_mes_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de certificación para el segundo mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutacertificacion',
            name='importe_mes_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de certificación para el tercer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutacertificacion',
            name='importe_mes_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de certificación para el cuarto mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutacertificacion',
            name='importe_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de certificación para el resto de años'),
        ),
        migrations.AlterField(
            model_name='hojaderutacertificacion',
            name='importe_presente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de certificación del presente año'),
        ),
        migrations.AlterField(
            model_name='hojaderutacertificacion',
            name='importe_proximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de certificación para el próximo año'),
        ),
        migrations.AlterField(
            model_name='hojaderutacertificacion',
            name='importe_resto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de certificación para el resto del año'),
        ),
        migrations.AlterField(
            model_name='hojaderutacertificacion',
            name='importe_siguiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de certificación para el siguiente año al próximo'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de cobro hasta fin del año anterior'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_mes_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de cobro para el primer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_mes_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de cobro para el segundo mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_mes_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de cobro para el tercer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_mes_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de cobro para el cuarto mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de cobro para el resto de años'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_presente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de cobro del presente año'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_proximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de cobro para el próximo año'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_resto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de cobro para el resto del año'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_siguiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de cobro para el siguiente año al próximo'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_ampliaciones_mes_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de ampliaciones para el primer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_ampliaciones_mes_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de ampliaciones para el segundo mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_ampliaciones_mes_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de ampliaciones para el tercer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_ampliaciones_mes_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de ampliaciones para el cuarto mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_ampliaciones_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de ampliaciones para el resto de años'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_ampliaciones_proximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de ampliaciones para el próximo año'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_ampliaciones_resto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de ampliaciones para el resto del año'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_ampliaciones_siguiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de ampliaciones para el siguiente año al próximo'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_central_mes_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de gastos de central para el primer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_central_mes_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de gastos de central para el segundo mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_central_mes_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de gastos de central para el tercer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_central_mes_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de gastos de central para el cuarto mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_central_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de gastos de central para el resto de años'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_central_proximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de gastos de central para el próximo año'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_central_resto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de gastos de central para el resto del año'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_central_siguiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de gastos de central para el siguiente año al próximo'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_contrato_mes_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción del contrato inicial para el primer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_contrato_mes_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción del contrato inicial para el segundo mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_contrato_mes_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción del contrato inicial para el tercer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_contrato_mes_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción del contrato inicial para el cuarto mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_contrato_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción del contrato inicial para el resto de años'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_contrato_proximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción del contrato inicial para el próximo año'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_contrato_resto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción del contrato inicial para el resto del año'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_contrato_siguiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción del contrato inicial para el siguiente año al próximo'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_coste_mes_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de coste directo para el primer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_coste_mes_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de coste directo para el segundo mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_coste_mes_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de coste directo para el tercer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_coste_mes_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de coste directo para el cuarto mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_coste_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de coste directo para el resto de años'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_coste_proximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de coste directo para el próximo año'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_coste_resto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de coste directo para el resto del año'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_coste_siguiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de coste directo para el siguiente año al próximo'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_delegacion_mes_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de gastos de delegación para el primer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_delegacion_mes_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de gastos de delegación para el segundo mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_delegacion_mes_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de gastos de delegación para el tercer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_delegacion_mes_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de gastos de delegación para el cuarto mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_delegacion_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de gastos de delegación para el resto de años'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_delegacion_proximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de gastos de delegación para el próximo año'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_delegacion_resto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de gastos de delegación para el resto del año'),
        ),
        migrations.AlterField(
            model_name='hojaderutaproduccion',
            name='importe_delegacion_siguiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de producción de gastos de delegación para el siguiente año al próximo'),
        ),
    ]
