# Generated by Django 2.2.7 on 2020-02-11 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0013_auto_20200206_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='hoja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='hdr.HojaDeRuta', verbose_name='hoja de ruta'),
        ),
    ]
