# Generated by Django 2.2.7 on 2020-03-10 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0014_auto_20200211_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaderuta',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='hdr_creadas', to=settings.AUTH_USER_MODEL, verbose_name='usuario de creación'),
        ),
        migrations.AlterField(
            model_name='hojaderuta',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='hdr_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='usuario de última modificación'),
        ),
    ]
