# Generated by Django 2.2.7 on 2020-06-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0015_auto_20200310_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaderuta',
            name='gasto_central_personalizado',
            field=models.BooleanField(default=False, verbose_name='% de gasto central personalizado'),
        ),
        migrations.AddField(
            model_name='hojaderuta',
            name='gasto_delegacion_personalizado',
            field=models.BooleanField(default=False, verbose_name='% de gasto delegación personalizado'),
        ),
    ]
