# Generated by Django 2.2.7 on 2022-07-02 14:32

from django.db import migrations, models
import hdr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0017_hojaderutacapitalfinanciero_hojaderutapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaderuta',
            name='cf_acreedor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='cf de acreedor'),
        ),
        migrations.AddField(
            model_name='hojaderuta',
            name='cf_deudor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='cf de deudor'),
        ),
        migrations.AddField(
            model_name='hojaderuta',
            name='periodo_cobro',
            field=models.IntegerField(default=30, validators=[hdr.models.validar_periodo], verbose_name='periodo de cobro'),
        ),
        migrations.AddField(
            model_name='hojaderuta',
            name='periodo_pago',
            field=models.IntegerField(default=30, validators=[hdr.models.validar_periodo], verbose_name='periodo de pago'),
        ),
    ]
