# Generated by Django 2.2.7 on 2022-07-11 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0033_obra_participacion_licuas'),
        ('hdr', '0018_auto_20220702_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaDeRutaPagoAuxiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='año')),
                ('cuarto', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], verbose_name='cuatrimestre')),
                ('importe_mes_1', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de pago para el primer mes del cuatrimestre')),
                ('importe_mes_2', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de pago para el segundo mes del cuatrimestre')),
                ('importe_mes_3', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de pago para el tercer mes del cuatrimestre')),
                ('importe_mes_4', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='importe de pago para el cuarto mes del cuatrimestre')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_auxiliar', to='general.Obra', verbose_name='obra asociada')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_auxiliar', to='hdr.HojaDeRutaPago', verbose_name='pago asociada')),
            ],
            options={
                'verbose_name': 'pago auxiliar de hoja de ruta',
                'verbose_name_plural': 'pagos auxiliares de hojas de ruta',
            },
        ),
    ]
