# Generated by Django 2.2.7 on 2022-07-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdr', '0020_hojaderutapago_pago_actualizar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaderutapago',
            name='importe_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de pago hasta fin del año anterior'),
        ),
        migrations.AlterField(
            model_name='hojaderutapago',
            name='importe_mes_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de pago para el primer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutapago',
            name='importe_mes_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de pago para el segundo mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutapago',
            name='importe_mes_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de pago para el tercer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutapago',
            name='importe_mes_4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de pago para el cuarto mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutapago',
            name='importe_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de pago para el resto de años'),
        ),
        migrations.AlterField(
            model_name='hojaderutapago',
            name='importe_presente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de pago del presente año'),
        ),
        migrations.AlterField(
            model_name='hojaderutapago',
            name='importe_proximo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de pago para el próximo año'),
        ),
        migrations.AlterField(
            model_name='hojaderutapago',
            name='importe_resto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de pago para el resto del año'),
        ),
        migrations.AlterField(
            model_name='hojaderutapago',
            name='importe_siguiente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de pago para el siguiente año al próximo'),
        ),
        migrations.AlterField(
            model_name='hojaderutapagoauxiliar',
            name='importe_mes_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de pago para el primer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutapagoauxiliar',
            name='importe_mes_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de pago para el segundo mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutapagoauxiliar',
            name='importe_mes_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de pago para el tercer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutapagoauxiliar',
            name='importe_mes_4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de pago para el cuarto mes del cuatrimestre'),
        ),
    ]
