# Generated by Django 2.2.7 on 2022-07-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0033_obra_participacion_licuas'),
        ('hdr', '0021_auto_20220714_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de cobro hasta fin del año anterior'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_mes_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de cobro para el primer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_mes_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de cobro para el segundo mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_mes_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de cobro para el tercer mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_mes_4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de cobro para el cuarto mes del cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de cobro para el resto de años'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_presente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de cobro del presente año'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_proximo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de cobro para el próximo año'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_resto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de cobro para el resto del año'),
        ),
        migrations.AlterField(
            model_name='hojaderutacobro',
            name='importe_siguiente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de cobro para el siguiente año al próximo'),
        ),
        migrations.CreateModel(
            name='HojaDeRutaCobroAuxiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='año')),
                ('cuarto', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], verbose_name='cuatrimestre')),
                ('importe_mes_1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de cobro para el primer mes del cuatrimestre')),
                ('importe_mes_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de cobro para el segundo mes del cuatrimestre')),
                ('importe_mes_3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de cobro para el tercer mes del cuatrimestre')),
                ('importe_mes_4', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='importe de cobro para el cuarto mes del cuatrimestre')),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobro_auxiliar', to='hdr.HojaDeRutaCobro', verbose_name='cobro asociada')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobro_auxiliar', to='general.Obra', verbose_name='obra asociada')),
            ],
            options={
                'verbose_name': 'cobro auxiliar de hoja de ruta',
                'verbose_name_plural': 'cobros auxiliares de hojas de ruta',
            },
        ),
    ]
